obs_common_subset: include an executable call to a debugging print routine, with if(.false.) in front, to avoid compiler warnings about an unused routine.
full_error:  remove final optional argument that isn't
currently being supported in this branch.

path_names_test_sampling_err_table: add netcdf utils
mod to the path_names file.



git-svn-id: https://svn-dares-dart.cgd.ucar.edu/DART/branches/recam@12626 dfa8782c-da17-4c45-ba5c-5625b50a00d6

Former-commit-id: 12a7b44746d449d491e08fdd8230439ab1af3a62